### ISSUE TITLE
Transfer repository to the OSUOSL Github org

### ISSUE THREAD

**Issue by emaadmanzoor** [chancez/igor-cli#13]
@ecnahc515 could you kindly fork this repository under the OSUOSL Github organisation?

Alternatively, you could do a repository transfer from the settings panel; I have added you as a collaborator. I don't have admin rights for the OSUOSL org so I couldn't transfer it myself.

**Comment by chancez** [comment]
I believe we've already got a fork, and I'm not entirely sure how ownership transfer works when there exists a fork. I can try to look into it.

**Comment by chancez** [comment]
@emaadmanzoor Turns out this repo isn't forked, only the riginal is. I don't have ownership of this repo so I can't transfer it. Why dont you transfer it to me, and I'll transfer it to the OSUOSL org.

**Comment by emaadmanzoor** [comment]
Done!

**Comment by chancez** [comment]
I don't seem to have ownership of the repo. I still cannot use the settings menu. Collaborator isnt enough.

**Comment by emaadmanzoor** [comment]
It appears to be owned by you now.
